name: dola-demo
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - pytorch-gpu>=2.6.0
  - pandas
  - pydantic
  - accelerate
  - sentencepiece
  - protobuf
  - faiss-gpu
  - sacremoses
  - bitsandbytes
  - pip
  - pip:
    - langchain
    - langchain-community
    - langchain-huggingface
    - evaluate
    - nltk
    - rouge_score
    - matplotlib
    - -e transformers-4.51.3-with-dola-score